force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <description>Store and manage individual job applications. Captures essential job-related details.</description>
    <label>Job Application</label>
    <nameField>
        <label>Job Application Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <description>A text field to store the name of the company where the job application is being sent.</description>
    <label>Company Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Job_Title__c</fullName>
    <description>A text field to keep track of the specific job title or position being applied for.</description>
    <label>Job Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>This picklist field will track the current status of the job application</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saved</fullName>
                <default>true</default>
                <label>Saved</label>
            </value>
            <value>
                <fullName>Applying</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewing</fullName>
            </value>
            <value>
                <fullName>Negotiating</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/JobApplicationContact__c/JobApplicationContact__c.object-meta.xml
<CustomObject>
    <description>A junction object associating multiple contacts for a Job application</description>
    <label>JobApplicationContact</label>
    <nameField>
        <label>JobApplicationContact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>JobApplicationContacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/JobApplicationContact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>JobApplicationContacts</relationshipLabel>
    <relationshipName>JobApplicationContacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/JobApplicationContact__c/fields/Job_Application__c.field-meta.xml
<CustomField>
    <fullName>Job_Application__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Job Application</label>
    <referenceTo>Job_Application__c</referenceTo>
    <relationshipLabel>JobApplicationContacts</relationshipLabel>
    <relationshipName>JobApplicationContacts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/JobApplicationContact__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>Role of the contact</description>
    <label>Role</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AssignPrimaryContactTest.cls
@IsTest
private with sharing class AssignPrimaryContactTest {
    //Test classes should be private unless they are being used as test data factories for shared data setup across multiple other test classes.
    @TestSetup
    private static void setupTestData() {
        // Create 3 test Contacts
        List<Contact> contacts = new List<Contact>();
        for (Integer i = 1; i <= 3; i++) {
            contacts.add(new Contact(
                FirstName = 'Test',
                LastName = 'Contact' + i,
                Email = 'test' + i + '@example.com'
            ));
        }
        insert contacts;

        // Create a test Job Applications with no primary contact assigned
        Job_Application__c jobApp = new Job_Application__c(
                Name = 'Test Job ',
                Status__c = 'Saved',
                Company_Name__c = 'ABC',
                Job_Title__c = 'Salesforce Developer'
            );
        insert jobApp;

        // Create junction records (JobApplicationContact__c) linking contacts to the job app.
        List<JobApplicationContact__c> jobContacts = new List<JobApplicationContact__c>();
        jobContacts.add(new JobApplicationContact__c(
            Name = 'JobContact1',
            Job_Application__c = jobApp.Id,
            Contact__c = contacts[0].Id,
            Role__c = 'HM'
        ));
        jobContacts.add(new JobApplicationContact__c(
            Name = 'JobContact2',
            Job_Application__c = jobApp.Id,
            Contact__c = contacts[1].Id,
            Role__c = 'HM'
        ));
        jobContacts.add(new JobApplicationContact__c(
            Name = 'JobContact3',
            Job_Application__c = jobApp.Id,
            Contact__c = contacts[2].Id,
            Role__c = 'HM'
        ));
        insert jobContacts;
    }

    @IsTest
    private static void testSetPrimaryContact() {
        // Retrieve the Job Applications
        List<Job_Application__c> jobs = [SELECT Id, Primary_Contact__c FROM Job_Application__c];

        // Call the method to set primary contact
        /*The method being tested should be called from within a test context using Test.startTest() and Test.stopTest()
        This is important for several reasons, but mainly to clearly define the method under test and 
        provide a fresh set of governor limits for the test transaction.*/
        Test.startTest();
        AssignPrimaryContact.setPrimaryContact(jobs);
        Test.stopTest();
        

        // Verify results
        List<Job_Application__c> updatedJobs = [SELECT Id, Primary_Contact__c FROM Job_Application__c];
        System.assertNotEquals(null, updatedJobs[0].Primary_Contact__c, 'Primary Contact should be set for Job');
        System.assertEquals(updatedJobs[0].Primary_Contact__c, [SELECT Contact__c FROM JobApplicationContact__c WHERE Job_Application__c = :updatedJobs[0].Id ORDER BY CreatedDate ASC LIMIT 1].Contact__c, 
                            'Primary Contact should match the first related contact');
    }
}